### ISSUE TITLE
Move to nixfmt

### ISSUE THREAD

**Issue by getchoo** [catppuccin/nix#127]
see https://github.com/NixOS/rfcs/pull/166. once there is a stable release, we should probably switch to it in order to conform to the wider community

**Comment by sgoudham** [comment]
If we're going to be caring about the formatting of nix code in this repository in the future. I'd really like it to be automatically carried out by CI, as previously demonstrated in [catppuccin/userstyles](https://github.com/catppuccin/userstyles/blob/76f6bd8c44044afc087b3ad0b5acd90560b1a901/.github/workflows/generate-format.yml#L46-L54). 

Carrying it out in CI removes the concern from both the maintainer and the contributor. Maintainers don't need to worry about commenting on formatting and contributors will have a smoother experience since just implementing a nixfmt lint check is a bit frustrating if they don't have a formatter set up already.
