### ISSUE TITLE
Hyprcursor theme is set to "MyCursor"

### ISSUE THREAD

**Issue by Different-Name** [catppuccin/nix#236]
https://github.com/catppuccin/nix/blob/73e06d5bd7ed34bdd0168030893ef8364fdc1d4a/modules/home-manager/hyprland.nix#L30

The hyprland module sets up environmental variables for the cursor, however these are overwritten later where the [example code from the hyprland wiki](https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/) is added to the hyprland config, setting the cursor theme to `MyCursor` instead of `catppuccin-${cursor.flavor}-${cursor.accent}-cursors`

**Comment by isabelroses** [comment]
Why do you have the example config still is my only question. Should you have removed that when configuring your config. `wayland.windowManager.hyprland.settings` or perhaps using `wayland.windowManager.hyprland.extraConfig`?

**Comment by Different-Name** [comment]
I'm not sure what you mean. I haven't provided my config, I've only referenced the module provided by this repo

**Comment by Different-Name** [comment]
I have my own config set up through home manager using `wayland.windowManager.hyprland.settings`
I am not using hyperland's default configuration
The hyprland module from this repo is adding the example code I linked into my configuration file, shown by the line I referenced in the issue
Am I missing a setting in the module?

**Comment by danielgafni** [comment]
I'm experiencing exactly the same problem. I was wondering why did my cursor break without me touching any settings around it. 

Turns out, the `hyprland` module from `cattpuccin-nix` 

1. Automatically enables `hyprcursors` 
2. Adds an import to my `hyprland.conf` like:


```
source=/nix/store/aan4vsxbqpg5y6l6nyqw91hk217sbnpq-hyprland-cursors.conf
```

And the referenced file contains:

```
› cat /nix/store/aan4vsxbqpg5y6l6nyqw91hk217sbnpq-hyprland-cursors.conf  
env = HYPRCURSOR_THEME,MyCursor
env = HYPRCURSOR_SIZE,24
```

I can see this is done [here](https://github.com/catppuccin/nix/blob/main/modules/home-manager/hyprland.nix#L28).

P.S. hardcoding `24` cursor size [here](https://github.com/catppuccin/nix/blob/main/modules/home-manager/hyprland.nix#L15) also doesn't seem to be correct.

**Comment by Different-Name** [comment]
Yes, this is the same issue I am experiencing. I believe it is a fault with the module @isabelroses

**Comment by Different-Name** [comment]
I'm on a recent commit of the unstable branch - https://github.com/NixOS/nixpkgs/commit/e9ee548d90ff586a6471b4ae80ae9cfcbceb3420

**Comment by danielgafni** [comment]
Oh, thanks, I didn't know hyprland enabled hyprcursors by default. 

> As a side note my best guess as to why its failing for you is because you're using an older version of nixpkgs that does not have the hyprcursor theme.

Nope, I'm on unstable and I have these packages built. 

I believe the problem was (partially) in using the old cursor theme name with capital letters. I [changed](https://github.com/danielgafni/nixos/pull/68/files#diff-aa952a65f44f514c7dc0fd47b34b4f09a3f93b5e4d9556e6dd0ed7a090bc5bc8R52) it to lowercase and the cursor works now. 

However, I'm not sure if I've done everything correctly. I don't even think hyprcursors is picking anything up at all, because `HYPRCURSOR_SIZE` and `HYPRCURSOR_THEME` does not affect anything. 

Only `home.pointerCursor.name` & `ome.pointerCursor.package` affect the theme generated in `~/.icons` / `~/.local/share/icons`. 

Honestly, I'm quite confused by relations between `home.pointerCursor`, `gtk.cursorTheme`, and `gtk.catppuccin.cursor`. 

`gtk.catppuccin.cursor` is setting `HYPRCURSOR_THEME`, but again, it's not really being picked up by hyprland. Clearly something is wrong on my side...

**Comment by isabelroses** [comment]
> I believe the problem was (partially) in using the old cursor theme name with capital letters. I [changed](https://github.com/danielgafni/nixos/pull/68/files#diff-aa952a65f44f514c7dc0fd47b34b4f09a3f93b5e4d9556e6dd0ed7a090bc5bc8R52) it to lowercase and the cursor works now.

Casing will be the downfall of catppuccin istg.

> Honestly, I'm quite confused by relations between `home.pointerCursor`, `gtk.cursorTheme`, and `gtk.catppuccin.cursor`.

`home.pointerCursor` Is a global alias in home-manager to setup all the cursor theming, which includes `gtk.cursorTheme`, catppuccin's `gtk.catppuccin.cursor` applies only the `gtk.cursorTheme` and not globally unlike `home.pointerCursor` which is why https://github.com/catppuccin/nix/pull/195 exists.

**Comment by Mange** [comment]
I'm not sure I get it, still.

Here's what the generated config will do:

1. The environment variables are set up with the user's values.

   https://github.com/catppuccin/nix/blob/1adbfeb44a54be0ae79eca751ba948a6faa3bb0f/modules/home-manager/hyprland.nix#L14-L16

2. Hyprland is then injected with statements that overwrite those values with placeholders.

   https://github.com/catppuccin/nix/blob/1adbfeb44a54be0ae79eca751ba948a6faa3bb0f/modules/home-manager/hyprland.nix#L28-L33

So spawning `hyprcursor` as a normal user will see the correct environment variables, but the `Hyprland` process, and any children spawned by it, will see `MyCursor` instead of the real value.

Why? Should I manually add `env=` statements to my extra config after this to go back to the real values again?

**Comment by Weathercold** [comment]
I'm in the process of fixing this but encountered a problem: if we only set `home.sessionVariables`, hyprland will inherit them when started from tty but not when started from certain display managers, as they don't start a login shell. At the same time, the user *really* should start hyprland from a login shell, e.g. by modifying the .desktop file or the startup command, otherwise the rc files won't be sourced, which results in strange bugs. See https://github.com/hyprwm/Hyprland/issues/2581.

I think we should set the variables in `home.sessionVariables`, @getchoo @isabelroses what do you think?
