### ISSUE TITLE
Ports for other home-manager modules

### ISSUE THREAD

**Issue by HeitorAugustoLN** [catppuccin/nix#279]
I intend to create a port for [Konsole](https://github.com/catppuccin/konsole). However, Konsole is configured by [plasma-manager](https://github.com/nix-community/plasma-manager), a module designed for home-manager. I am uncertain whether this port should be included within the home-manager options or if it necessitates the creation of a separate module specifically for plasma-manager.

**Comment by getchoo** [comment]
the potential for plasma-manager support specifically is already being tracked in #215

for other external modules, i would prefer a similar dedicated issue as this is something that would need to be addressed on a case by case basis rather than allowing any or none of them

closing this as a duplicate. thanks though!
