### ISSUE TITLE
Discrepencies between running delta inside lazygit and in the terminal

### ISSUE THREAD

**Issue by multivac61** [catppuccin/nix#328]
Thank you for a wonderful project.

I've been using it to rice my system thoroughly, it is a wonderful module.

Using `lazygit` today I noticed a discrepancy in the green/red background between using delta as its pager or in standalone. Why could that be?

![CleanShot 2024-09-03 at 19 18 59@2x](https://github.com/user-attachments/assets/69082db8-15c0-49d4-bac1-bcf064c198d9)

![CleanShot 2024-09-03 at 19 18 50@2x](https://github.com/user-attachments/assets/7724afc8-83f8-4e1b-8f07-5f8f9b8a617e)

[Here's the nixos config for home-manager (nix-darwin)](https://github.com/multivac61/nixos-config/blob/main/modules/shared/home.nix#L34)

**Comment by uncenter** [comment]
I would assume this is an issue with the lazygit theme, so I would report it there. As ctp-nix would just be loading the themes from the upstream repo, it's unlikely ctp-nix is causing the issue unless you've tested with manually setting the lazygit theme instead of using ctp-nix and could not reproduce.

**Comment by multivac61** [comment]
Thank you, closing in favour of https://github.com/catppuccin/lazygit/issues/49
